- name: Run PowerShell command on Windows host
  hosts: webservers
  become: true
  tasks:
    - name: Run w32tm /query /peers command
      win_shell: w32tm /query /peers
      register: result